name: Telefonistka
# Controls when the workflow will run
# "closed" is used for promoting changes
# "opened"/"synchronize" are needed to warn on drift
on:
  pull_request:
    types:
      - closed
      - opened
      - synchronize
    branches: [ "main" ]

jobs:
  telefonistka:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/rafaelherrero/telefonistka:test
    steps:
      - name: Run Telefonistka
        run: telefonistka event
        env:
          GITHUB_OAUTH_TOKEN: ${{ secrets.GH_TOKEN }}
          APPROVER_GITHUB_OAUTH_TOKEN: ${{ secrets.GH_TOKEN }}
          TEMPLATES_PATH: "/srv/templates/"
